'use strict';function b(a){return document.createElement(a)}const d={},e={},f={},g=b("button"),h=b("button"),k=b("button"),l=b("button"),m=b("a"),n=b("p"),p=b("h1");f.de={done:"Geraten!",b:"Leicht zu raten, eine Minute Zeit",c:"Aus und vorbei!",go:"Los!",g:"Schwer zu raten, zwei Minuten Zeit",f:"Fleissig raten!",a:"Alle bis auf Einen wegschauen! Dann drücken Sie Weiter für einen Begriff, den die Anderen raten sollen.",next:"Weiter",h:"Wenn Sie sich den Begriff gemerkt haben, drücken Sie Leicht, oder Schwer und die Zeit läuft!",i:"Quelltext",j:"Geschafft!",title:"Ratespiel"};
e.de=[["Abgeordneter","Abgeordnete"],["Abwassertechniker","Abwassertechnikerin"],["Ajatollah"],["Altenpflegehelfer","Altenpflegehelferin"],["Altenpfleger","Altenpflegerin"],["Amme"],["Anlagenmechaniker","Anlagenmechanikerin"],["Anästhesist","Anästhesistin"],["Arzthelfer","Arzthelferin"],["Asphaltbauer","Asphaltbauerin"],["Augenoptiker","Augenoptikerin"],["Automatenfachmann","Automatenfachfrau"],["Autoverkäufer","Autoverkäuferin"],["Baby"],["Bademeister","Bademeisterin"],["Baggerführer","Baggerführerin"],
["Bankier","Bankierin"],["Bankkaufmann","Bankkauffrau"],["Bauarbeiter","Bauarbeiterin"],["Bauer","Bäuerin"],["Baustoffprüfer","Baustoffprüferin"],["Bauzeichner","Bauzeichnerin"],["Beamter","Beamtin"],["Bergbautechnologe","Bergbautechnologin"],["Berufskraftfahrer","Berufskraftfahrerin"],["Betriebswirt","Betriebswirtin"],["Binnenschiffer","Binnenschifferin"],["Biologielaborant","Biologielaborantin"],["Botschafter","Botschafterin"],["Brauer","Brauerin"],["Buchhändler","Buchhändlerin"],["Bäcker","Bäckerin"],
["Bürgermeister","Bürgermeisterin"],["Bürokaufmann","Bürokauffrau"],["Chauffeur","Chauffeurin"],["Chemielaborant","Chemielaborantin"],["Chirurg","Chirurgin"],["Clown"],["Dachdecker","Dachdeckerin"],["Dandy"],["Dealer","Dealerin"],["Demagoge","Demagogein"],["Diktator","Diktatorin"],["Diplomat","Diplomatin"],["Direktor","Direktorin"],["Dirigent","Dirigentin"],["Diätassistent","Diätassistentin"],["Dolmetscher","Dolmetscherin"],["Domina"],["Drag Queen"],["Drogist","Drogistin"],["Edelmann","Edelfrau"],
["Eisenbahner","Eisenbahnerin"],["Elektroniker","Elektronikerin"],["Engelmacherin"],["Ergotherapeut","Ergotherapeutin"],["Erzieher","Erzieherin"],["Eventmanager","Eventmanagerin"],["Fahrzeuginnenausstatter","Fahrzeuginnenausstatterin"],["Fahrzeuglackierer","Fahrzeuglackiererin"],["Fernfahrer","Fernfahrerin"],["Fertigungsmechaniker","Fertigungsmechanikerin"],["Feuerwehrmann","Feuerwehrfrau"],["Filmemacher","Filmemacherin"],["Fitnesstrainer","Fitnesstrainerin"],["Flachglasmechaniker","Flachglasmechanikerin"],
["Fleischer","Fleischerin"],["Florist","Floristin"],["Flüchtling"],["Forstwirt","Forstwirtin"],["Fotograf","Fotografin"],["Fremdsprachenkorrespondent","Fremdsprachenkorrespondentin"],["Funker","Funkerin"],["Galerist","Galeristin"],["Gastwirt","Gastwirtin"],["Gebäudereiniger","Gebäudereinigerin"],["Geigenbauer","Geigenbauerin"],["Geiger","Geigerin"],["Geomatiker","Geomatikerin"],["Gerber","Gerberin"],["Gerüstbauer","Gerüstbauerin"],["Glasapparatebauer","Glasapparatebauerin"],["Gleisbauer","Gleisbauerin"],
["Goldschmied","Goldschmiedin"],["Grafikdesigner","Grafikdesignerin"],["Groupie"],["Gutsherr","Gutsherrin"],["Gynekologe","Gynekologin"],["Gärtner","Gärtnerin"],["Hafenarbeiter","Hafenarbeiterin"],["Hausmann","Hausfrau"],["Hausmeister","Hausmeisterin"],["Hebamme"],["Heilerziehungspfleger","Heilerziehungspflegerin"],["Heiratsschwindler","Heiratsschwindlerin"],["Herrenausstatter","Herrenausstatterin"],["Hochstapler","Hochstaplerin"],["Hotelmanager","Hotelmanagerin"],["Hure"],["Hörgeräteakustiker","Hörgeräteakustikerin"],
["Immobilienkaufmann","Immobilienkauffrau"],["Immobilienmakler","Immobilienmaklerin"],["Informatiker","Informatikerin"],["Investmentfondskaufmann","Investmentfondskauffrau"],["Journalist","Journalistin"],["Justizvollzugsbeamter","Justizvollzugsbeamtin"],["Kanalbauer","Kanalbauerin"],["Kanzler","Kanzlerin"],["Kapitän"],["Karosseriebauer","Karosseriebauerin"],["Kaufmann","Kauffrau"],["Kindergärtnerin"],["Kinderkrankenpfleger","Kinderkrankenpflegerin"],["Kinderpfleger","Kinderpflegerin"],["Klavierlehrer",
"Klavierlehrerin"],["Kleinkrimmineller","Kleinkrimminelle"],["Klofrau"],["Koch","Köchin"],["Kommunikationsdesigner","Kommunikationsdesignerin"],["Komponist","Komponistin"],["Konditor","Konditorin"],["Konstruktionsmechaniker","Konstruktionsmechanikerin"],["Kosmetiker","Kosmetikerin"],["Krankenpflegehelfer","Krankenpflegehelferin"],["Krankenpfleger","Krankenpflegerin"],["Kurier"],["Laborant","Laborantin"],["Lackierer","Lackiererin"],["Landwirt","Landwirtin"],["Lebensmittelverkäufer","Lebensmittelverkäuferin"],
["Lehrer","Lehrerin"],["Logopäde","Logopädin"],["Maler","Malerin"],["Maskenbildner","Maskenbildnerin"],["Masseur","Masseurin"],["Matrose"],["Maurer","Maurerin"],["Mechaniker","Mechanikerin"],["Metallbauer","Metallbauerin"],["Minister","Ministerin"],["Modedesigner","Modedesignerin"],["Model"],["Modellbauer","Modellbauerin"],["Monteur"],["Musiktherapeut","Musiktherapeutin"],["Mutter"],["Möbelbauer","Möbelbauerin"],["Mönch","Nonne"],["Müller","Müllerin"],["Müllmann","Müllfrau"],["Notar","Notarin"],["Notfallsanitäter",
"Notfallsanitäterin"],["Oberflächenbeschichter","Oberflächenbeschichterin"],["Offizier","Offizierin"],["Optiker","Optikerin"],["Organist","Organistin"],["Packmitteltechnologe","Packmitteltechnologin"],["Pantomime","Pantomimin"],["Panzerfahrer","Panzerfahrerin"],["Papiermacher","Papiermacherin"],["Papst"],["Parteivorsitzender","Parteivorsitzende"],["Patentanwalt","Patentanwältin"],["Pfarrer","Pfarrerin"],["Pharmakant","Pharmakantin"],["Physiker","Physikerin"],["Physiotherapeut","Physiotherapeutin"],
["Pianist","Pianistin"],["Pilot","Pilotin"],["Priester","Priesterin"],["Produktdesigner","Produktdesignerin"],["Professor","Professorin"],["Putzmann","Putzfrau"],["Radiologe","Radiologin"],["Rechtsanwalt","Rechtsanwältin"],["Rentier"],["Reporter","Reporterin"],["Restaurantfachmann","Restaurantfachfrau"],["Rettungsassistent","Rettungsassistentin"],["Rettungsschwimmer","Rettungsschwimmerin"],["Richter","Richterin"],["Ritter"],["Rohrleitungsbauer","Rohrleitungsbauerin"],["Schauspieler","Schauspielerin"],
["Schleuser"],["Schmuggler"],["Schneemann","Schneefrau"],["Schneider","Schneiderin"],["Schornsteinfeger","Schornsteinfegerin"],["Schrankenwärter","Schrankenwärterin"],["Schreiner"],["Schriftsteller","Schriftstellerin"],["Schuster"],["Schönheitschirurg","Schönheitschirurgin"],["Schüler","Schülerin"],["Selbstmordattentäter","Selbstmordattentäterin"],["Softwareentwickler","Softwareentwicklerin"],["Soldat"],["Sozialforscher","Sozialforscherin"],["Sozialpädagoge","Sozialpädagogin"],["Spion"],["Staatsanwalt",
"Staatsanwältin"],["Steuerberater","Steuerberaterin"],["Strafgefangener","Strafgefangene"],["Strassenbauer","Strassenbauerin"],["Stripper"],["Sänger","Sängerin"],["Tankwart","Tankwärtin"],["Tierpfleger","Tierpflegerin"],["Tischler","Tischlerin"],["Totengräber","Totengräberin"],["Tourismuskaufmann","Tourismuskauffrau"],["Transvestit","Transvestitin"],["Uhrmacher","Uhrmacherin"],["Umweltschützer","Umweltschützerin"],["Verbrecher"],["Verkäufer","Verkäuferin"],["Vermessungstechniker","Vermessungstechnikerin"],
["Versicherungsvertreter","Versicherungsvertreterin"],["Verwaltungsfachangestellter","Verwaltungsfachangestellte"],["Wachmann"],["Werkstoffprüfer","Werkstoffprüferin"],["Winzer","Winzerin"],["Zahnarzt","Zahnarztin"],["Zimmermann"]];d.de=e.de.map((a,c)=>c);function q(a){document.body.appendChild(a)}function r(a){document.body.insertBefore(a,m)}function t(a){document.body.removeChild(a)}function v(a){function c(){if(a!==-1){const w=a/60>>0,u=a-w*60;p.textContent=w+":"+(u>9?u:"0"+u);if(a>0)setTimeout(c,1E3);else{n.textContent=f.de.a;p.textContent=f.de.c;t(h);r(l)}a-=1}}h.onclick=function(){a=-1;n.textContent=f.de.a;p.textContent=f.de.j;t(h);r(l)};n.textContent=f.de.f;t(k);t(g);r(h);c()}
function x(){function a(a){return Math.floor(Math.random()*a)}var c=d.de.splice(a(d.de.length),1);c=e.de[c];return c.length>0?c[a(c.length)]:c[0]}
window.setup=function(){g.onclick=()=>v(60);g.textContent=f.de.b;h.textContent=f.de.done;k.onclick=()=>v(120);k.textContent=f.de.g;l.onclick=function(){if(d.length===0){d.length=e.length;d.fill().map((a,c)=>d[c]=c)}p.textContent=x();n.textContent=f.de.h;t(l);r(g);r(k)};l.textContent=f.de.next;m.href="https://github.com/kassapo/quiz";m.id="sources";m.textContent=f.de.i;n.textContent=f.de.a;p.textContent=f.de.title;q(p);q(n);q(l);q(m)};
